//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_Game_Platform.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Capstone_Game_Platform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG_L1 {
            get {
                object obj = ResourceManager.GetObject("BG_L1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG_L11 {
            get {
                object obj = ResourceManager.GetObject("BG_L11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bolt_L1 {
            get {
                object obj = ResourceManager.GetObject("Bolt_L1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bolt_L2 {
            get {
                object obj = ResourceManager.GetObject("Bolt_L2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_L1 {
            get {
                object obj = ResourceManager.GetObject("Cloud_L1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_L1_Dark {
            get {
                object obj = ResourceManager.GetObject("Cloud_L1_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_L1_Light {
            get {
                object obj = ResourceManager.GetObject("Cloud_L1_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_L1_Medium {
            get {
                object obj = ResourceManager.GetObject("Cloud_L1_Medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_L11 {
            get {
                object obj = ResourceManager.GetObject("Cloud_L11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_L2_Dark {
            get {
                object obj = ResourceManager.GetObject("Cloud_L2_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_L2_Med {
            get {
                object obj = ResourceManager.GetObject("Cloud_L2_Med", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_L3_Dark {
            get {
                object obj = ResourceManager.GetObject("Cloud_L3_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_L3_Low {
            get {
                object obj = ResourceManager.GetObject("Cloud_L3_Low", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_L3_Low1 {
            get {
                object obj = ResourceManager.GetObject("Cloud_L3_Low1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud_L3_Med {
            get {
                object obj = ResourceManager.GetObject("Cloud_L3_Med", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloud_PNG27 {
            get {
                object obj = ResourceManager.GetObject("cloud_PNG27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;cloud9 xmlns:CO=&quot;urn:Cloud9Data&quot;&gt;
        ///  &lt;player&gt;
        ///    &lt;player_ID&gt;1&lt;/player_ID&gt;
        ///    &lt;player_name&gt;DewDrop&lt;/player_name&gt;
        ///    &lt;char_level&gt;1&lt;/char_level&gt;
        ///    &lt;char_points&gt;0&lt;/char_points&gt;
        ///  &lt;/player&gt;
        ///  &lt;player_history&gt;
        ///    &lt;player_ID&gt;1&lt;/player_ID&gt;
        ///    &lt;level_ID&gt;1&lt;/level_ID&gt;
        ///    &lt;life_count&gt;0&lt;/life_count&gt;
        ///    &lt;points&gt;0&lt;/points&gt;
        ///    &lt;level_time&gt;0&lt;/level_time&gt;
        ///    &lt;special_count&gt;0&lt;/special_count&gt;
        ///    &lt;monster_count&gt;0&lt;/monster_count&gt;
        ///    &lt;last_played [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cloud9DataXML {
            get {
                return ResourceManager.GetString("Cloud9DataXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:CO=&quot;urn:Cloud9Data&quot;  targetNamespace=&quot;urn:Cloud9Data&quot;&gt;
        ///  &lt;xs:element name=&quot;player_ID&quot; type=&quot;xs:integer&quot;/&gt;
        ///  &lt;xs:element name=&quot;player_name&quot; type=&quot;xs:string&quot;/&gt;
        ///  &lt;xs:element name=&quot;char_level&quot; type=&quot;xs:integer&quot;/&gt;
        ///  &lt;xs:element name=&quot;char_points&quot; type=&quot;xs:integer&quot;/&gt;
        ///  &lt;xs:element name=&quot;level_ID&quot; type=&quot;xs:integer&quot;/&gt;
        ///  &lt;xs:element name=&quot;life_count&quot; type=&quot;xs:integer&quot;/&gt;
        ///  &lt;xs:element [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cloud9DataXSD {
            get {
                return ResourceManager.GetString("Cloud9DataXSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Floor_Block_L1 {
            get {
                object obj = ResourceManager.GetObject("Floor_Block_L1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Floor_Block_L1_1 {
            get {
                object obj = ResourceManager.GetObject("Floor_Block_L1 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Floor_Block_L2 {
            get {
                object obj = ResourceManager.GetObject("Floor_Block_L2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Floor_Block_L3 {
            get {
                object obj = ResourceManager.GetObject("Floor_Block_L3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Moon {
            get {
                object obj = ResourceManager.GetObject("Moon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Portal_Closed {
            get {
                object obj = ResourceManager.GetObject("Portal_Closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Portal_Closed_High {
            get {
                object obj = ResourceManager.GetObject("Portal_Closed_High", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Portal_Closed_L2_High {
            get {
                object obj = ResourceManager.GetObject("Portal_Closed_L2_High", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Raindrop {
            get {
                object obj = ResourceManager.GetObject("Raindrop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Raindrop1 {
            get {
                object obj = ResourceManager.GetObject("Raindrop1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_L1 {
            get {
                object obj = ResourceManager.GetObject("Star_L1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_L1_Dark {
            get {
                object obj = ResourceManager.GetObject("Star_L1_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_L1_Light {
            get {
                object obj = ResourceManager.GetObject("Star_L1_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_L1_Medium {
            get {
                object obj = ResourceManager.GetObject("Star_L1_Medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_L2_Dark {
            get {
                object obj = ResourceManager.GetObject("Star_L2_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_L2_Light {
            get {
                object obj = ResourceManager.GetObject("Star_L2_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_L2_Med {
            get {
                object obj = ResourceManager.GetObject("Star_L2_Med", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_L3_Dark {
            get {
                object obj = ResourceManager.GetObject("Star_L3_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_L3_Light {
            get {
                object obj = ResourceManager.GetObject("Star_L3_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star_L3_Med {
            get {
                object obj = ResourceManager.GetObject("Star_L3_Med", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sun {
            get {
                object obj = ResourceManager.GetObject("Sun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tornado_High {
            get {
                object obj = ResourceManager.GetObject("Tornado_High", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tornado_L1_Dark {
            get {
                object obj = ResourceManager.GetObject("Tornado_L1_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tornado_L2_Dark {
            get {
                object obj = ResourceManager.GetObject("Tornado_L2_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud9Data.xml.
        /// </summary>
        internal static string XMLDBName {
            get {
                return ResourceManager.GetString("XMLDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud9Data.
        /// </summary>
        internal static string XMLNSURN {
            get {
                return ResourceManager.GetString("XMLNSURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud9Data.xsd.
        /// </summary>
        internal static string XSDDBName {
            get {
                return ResourceManager.GetString("XSDDBName", resourceCulture);
            }
        }
    }
}
