// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Sonya Try at Level 1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinWindow uIPlayerStatsWindow = this.UICloud9Window.UICloud9Client.UIPlayerStatsWindow;
            WinWindow uIPlayerStatsWindow1 = this.UIPlayerStatsWindow;
            WinWindow uIContinueWindow = this.UICloud9Window.UICloud9Client.UIContinueWindow;
            WinWindow uINewGameWindow = this.UICloud9Window.UICloud9Client.UINewGameWindow;
            WinWindow uINextWindow = this.UITheStoryWindow.UITheStoryClient.UINextWindow;
            WinWindow uIBeginWindow = this.UITheStoryWindow.UITheStoryClient.UIBeginWindow;
            WinClient uICloud9Level1Client = this.UICloud9Level1Window.UICloud9Level1Client;
            WinWindow uIContinueWindow1 = this.UIDeathBoxWindow.UIDeathBoxClient.UIContinueWindow;
            WinWindow uIBackgroundWindow = this.UICloud9Level1Window.UICloud9Level1Client.UIBackgroundWindow;
            WinButton uIContinueButton = this.UIDeathBoxWindow.UIContinueWindow.UIContinueButton;
            WinWindow uIExitGameWindow = this.UIDeathBoxWindow.UIDeathBoxClient.UIExitGameWindow;
            #endregion

            // Click 'Player Stats' window
            Mouse.Click(uIPlayerStatsWindow, new Point(372, 200));

            // Click 'PlayerStats' window
            Mouse.Click(uIPlayerStatsWindow1, new Point(1294, 74));

            // Click 'Continue' window
            Mouse.Click(uIContinueWindow, new Point(389, 186));

            // Last mouse action was not recorded.

            // Click 'New Game' window
            Mouse.Click(uINewGameWindow, new Point(374, 169));

            // Click 'Next' window
            Mouse.Click(uINextWindow, new Point(346, 268));

            // Click 'Next' window
            Mouse.Click(uINextWindow, new Point(347, 267));

            // Click 'Next' window
            Mouse.Click(uINextWindow, new Point(347, 267));

            // Click 'Next' window
            Mouse.Click(uINextWindow, new Point(347, 267));

            // Click 'Next' window
            Mouse.Click(uINextWindow, new Point(347, 267));

            // Click 'Next' window
            Mouse.Click(uINextWindow, new Point(347, 267));

            // Click 'Begin!!' window
            Mouse.Click(uIBeginWindow, new Point(347, 267));

            // Type '{Space}{Right}{Right}{Right}{Space}{Space}{Right}{Space}{Space}{Down}{Right}{Space}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Right}{Right}{Right}{Right}{Space}{Right}{Space}{Space}{Space}{Space}{Right}{Right}{Right}{Right}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys, ModifierKeys.None);

            // Type '{Right}{Space}{Right}{Space}{Right}{Space}{Space}{Right}{Down}{Space}{Space}{Space}{Space}{Space}{Space}{Down}{Up}{Down}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys1, ModifierKeys.None);

            // Click 'Continue' window
            Mouse.Click(uIContinueWindow1, new Point(377, 245));

            // Type '{Right}{Space}{Right}{Space}{Space}{Down}{Space}{Space}{Down}{Down}{Down}{Left}{Left}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Left}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys2, ModifierKeys.None);

            // Type '{Left}{Right}{Right}{Space}{Space}{Right}{Right}{Space}{Space}{Right}v{Right}{Space}{Right}{Right}{Space}{Space}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys3, ModifierKeys.None);

            // Type '{Right}{Right}{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys4, ModifierKeys.None);

            // Click 'background' window
            Mouse.Click(uIBackgroundWindow, new Point(1029, 556));

            // Type '{Space}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Left}{Space}{Right}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys5, ModifierKeys.None);

            // Type '{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys6, ModifierKeys.None);

            // Type '{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Right}{Space}{Space}{Right}{Space}{Space}{Right}{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys7, ModifierKeys.None);

            // Type '{Right}{Space}{Space}{Space}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys8, ModifierKeys.None);

            // Type '{Space}' in 'Continue' button
            Keyboard.SendKeys(uIContinueButton, this.RecordedMethod1Params.UIContinueButtonSendKeys, ModifierKeys.None);

            // Type '{Right}{Right}{Right}{Right}{Right}{Space}{Right}{Space}{Space}{Right}{Space}{Right}{Space}{Right}{Space}{Space}{Space}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Left}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys9, ModifierKeys.None);

            // Type '{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Right}{Space}{Space}{Down}{Down}{Down}{Down}{Down}{Space}{Down}{Down}{Space}{Down}{Down}{Down}{Down}{Left}{Space}{Left}{Space}{Left}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys10, ModifierKeys.None);

            // Type '{Enter}' in 'Continue' button
            Keyboard.SendKeys(uIContinueButton, this.RecordedMethod1Params.UIContinueButtonSendKeys1, ModifierKeys.None);

            // Type '{Right}{Right}{Right}{Right}{Right}{Space}{Right}{Right}{Right}{Right}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
            Keyboard.SendKeys(uICloud9Level1Client, this.RecordedMethod1Params.UICloud9Level1ClientSendKeys11, ModifierKeys.None);

            // Click 'Exit Game' window
            Mouse.Click(uIExitGameWindow, new Point(386, 242));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UICloud9Window UICloud9Window
        {
            get
            {
                if ((this.mUICloud9Window == null))
                {
                    this.mUICloud9Window = new UICloud9Window();
                }
                return this.mUICloud9Window;
            }
        }
        
        public UIPlayerStatsWindow UIPlayerStatsWindow
        {
            get
            {
                if ((this.mUIPlayerStatsWindow == null))
                {
                    this.mUIPlayerStatsWindow = new UIPlayerStatsWindow();
                }
                return this.mUIPlayerStatsWindow;
            }
        }
        
        public UITheStoryWindow UITheStoryWindow
        {
            get
            {
                if ((this.mUITheStoryWindow == null))
                {
                    this.mUITheStoryWindow = new UITheStoryWindow();
                }
                return this.mUITheStoryWindow;
            }
        }
        
        public UICloud9Level1Window UICloud9Level1Window
        {
            get
            {
                if ((this.mUICloud9Level1Window == null))
                {
                    this.mUICloud9Level1Window = new UICloud9Level1Window();
                }
                return this.mUICloud9Level1Window;
            }
        }
        
        public UIDeathBoxWindow UIDeathBoxWindow
        {
            get
            {
                if ((this.mUIDeathBoxWindow == null))
                {
                    this.mUIDeathBoxWindow = new UIDeathBoxWindow();
                }
                return this.mUIDeathBoxWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UICloud9Window mUICloud9Window;
        
        private UIPlayerStatsWindow mUIPlayerStatsWindow;
        
        private UITheStoryWindow mUITheStoryWindow;
        
        private UICloud9Level1Window mUICloud9Level1Window;
        
        private UIDeathBoxWindow mUIDeathBoxWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '{Space}{Right}{Right}{Right}{Space}{Space}{Right}{Space}{Space}{Down}{Right}{Space}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Right}{Right}{Right}{Right}{Space}{Right}{Space}{Space}{Space}{Space}{Right}{Right}{Right}{Right}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys = @"{Space}{Right}{Right}{Right}{Space}{Space}{Right}{Space}{Space}{Down}{Right}{Space}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Right}{Right}{Right}{Right}{Space}{Right}{Space}{Space}{Space}{Space}{Right}{Right}{Right}{Right}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}";
        
        /// <summary>
        /// Type '{Right}{Space}{Right}{Space}{Right}{Space}{Space}{Right}{Down}{Space}{Space}{Space}{Space}{Space}{Space}{Down}{Up}{Down}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys1 = "{Right}{Space}{Right}{Space}{Right}{Space}{Space}{Right}{Down}{Space}{Space}{Spac" +
            "e}{Space}{Space}{Space}{Down}{Up}{Down}";
        
        /// <summary>
        /// Type '{Right}{Space}{Right}{Space}{Space}{Down}{Space}{Space}{Down}{Down}{Down}{Left}{Left}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Left}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys2 = @"{Right}{Space}{Right}{Space}{Space}{Down}{Space}{Space}{Down}{Down}{Down}{Left}{Left}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Left}";
        
        /// <summary>
        /// Type '{Left}{Right}{Right}{Space}{Space}{Right}{Right}{Space}{Space}{Right}v{Right}{Space}{Right}{Right}{Space}{Space}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys3 = "{Left}{Right}{Right}{Space}{Space}{Right}{Right}{Space}{Space}{Right}v{Right}{Spa" +
            "ce}{Right}{Right}{Space}{Space}";
        
        /// <summary>
        /// Type '{Right}{Right}{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys4 = "{Right}{Right}{Right}{Right}{Right}{Right}";
        
        /// <summary>
        /// Type '{Space}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Left}{Space}{Right}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys5 = @"{Space}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Left}{Space}{Right}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}";
        
        /// <summary>
        /// Type '{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys6 = "{Right}{Right}{Right}{Right}";
        
        /// <summary>
        /// Type '{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Right}{Space}{Space}{Right}{Space}{Space}{Right}{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys7 = "{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Right}{Space}{Spa" +
            "ce}{Right}{Space}{Space}{Right}{Right}{Right}{Right}{Right}";
        
        /// <summary>
        /// Type '{Right}{Space}{Space}{Space}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys8 = "{Right}{Space}{Space}{Space}";
        
        /// <summary>
        /// Type '{Space}' in 'Continue' button
        /// </summary>
        public string UIContinueButtonSendKeys = "{Space}";
        
        /// <summary>
        /// Type '{Right}{Right}{Right}{Right}{Right}{Space}{Right}{Space}{Space}{Right}{Space}{Right}{Space}{Right}{Space}{Space}{Space}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Left}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys9 = @"{Right}{Right}{Right}{Right}{Right}{Space}{Right}{Space}{Space}{Right}{Space}{Right}{Space}{Right}{Space}{Space}{Space}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Left}";
        
        /// <summary>
        /// Type '{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Right}{Space}{Space}{Down}{Down}{Down}{Down}{Down}{Space}{Down}{Down}{Space}{Down}{Down}{Down}{Down}{Left}{Space}{Left}{Space}{Left}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys10 = @"{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Space}{Right}{Space}{Space}{Down}{Down}{Down}{Down}{Down}{Space}{Down}{Down}{Space}{Down}{Down}{Down}{Down}{Left}{Space}{Left}{Space}{Left}";
        
        /// <summary>
        /// Type '{Enter}' in 'Continue' button
        /// </summary>
        public string UIContinueButtonSendKeys1 = "{Enter}";
        
        /// <summary>
        /// Type '{Right}{Right}{Right}{Right}{Right}{Space}{Right}{Right}{Right}{Right}{Space}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}' in 'Cloud 9 - Level 1' client
        /// </summary>
        public string UICloud9Level1ClientSendKeys11 = "{Right}{Right}{Right}{Right}{Right}{Space}{Right}{Right}{Right}{Right}{Space}{Rig" +
            "ht}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICloud9Window : WinWindow
    {
        
        public UICloud9Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Cloud 9";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Cloud 9");
            #endregion
        }
        
        #region Properties
        public UICloud9Client UICloud9Client
        {
            get
            {
                if ((this.mUICloud9Client == null))
                {
                    this.mUICloud9Client = new UICloud9Client(this);
                }
                return this.mUICloud9Client;
            }
        }
        #endregion
        
        #region Fields
        private UICloud9Client mUICloud9Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICloud9Client : WinClient
    {
        
        public UICloud9Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Cloud 9";
            this.WindowTitles.Add("Cloud 9");
            #endregion
        }
        
        #region Properties
        public WinWindow UIPlayerStatsWindow
        {
            get
            {
                if ((this.mUIPlayerStatsWindow == null))
                {
                    this.mUIPlayerStatsWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIPlayerStatsWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Player Stats";
                    this.mUIPlayerStatsWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIPlayerStatsWindow.WindowTitles.Add("Cloud 9");
                    #endregion
                }
                return this.mUIPlayerStatsWindow;
            }
        }
        
        public WinWindow UIContinueWindow
        {
            get
            {
                if ((this.mUIContinueWindow == null))
                {
                    this.mUIContinueWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIContinueWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Continue";
                    this.mUIContinueWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIContinueWindow.WindowTitles.Add("Cloud 9");
                    #endregion
                }
                return this.mUIContinueWindow;
            }
        }
        
        public WinWindow UINewGameWindow
        {
            get
            {
                if ((this.mUINewGameWindow == null))
                {
                    this.mUINewGameWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUINewGameWindow.SearchProperties[WinWindow.PropertyNames.Name] = "New Game";
                    this.mUINewGameWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUINewGameWindow.WindowTitles.Add("Cloud 9");
                    #endregion
                }
                return this.mUINewGameWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIPlayerStatsWindow;
        
        private WinWindow mUIContinueWindow;
        
        private WinWindow mUINewGameWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPlayerStatsWindow : WinWindow
    {
        
        public UIPlayerStatsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "PlayerStats";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("PlayerStats");
            #endregion
        }
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITheStoryWindow : WinWindow
    {
        
        public UITheStoryWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "The Story";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("The Story");
            #endregion
        }
        
        #region Properties
        public UITheStoryClient UITheStoryClient
        {
            get
            {
                if ((this.mUITheStoryClient == null))
                {
                    this.mUITheStoryClient = new UITheStoryClient(this);
                }
                return this.mUITheStoryClient;
            }
        }
        #endregion
        
        #region Fields
        private UITheStoryClient mUITheStoryClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITheStoryClient : WinClient
    {
        
        public UITheStoryClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "The Story";
            this.WindowTitles.Add("The Story");
            #endregion
        }
        
        #region Properties
        public WinWindow UINextWindow
        {
            get
            {
                if ((this.mUINextWindow == null))
                {
                    this.mUINextWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUINextWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Next";
                    this.mUINextWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUINextWindow.WindowTitles.Add("The Story");
                    #endregion
                }
                return this.mUINextWindow;
            }
        }
        
        public WinWindow UIBeginWindow
        {
            get
            {
                if ((this.mUIBeginWindow == null))
                {
                    this.mUIBeginWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIBeginWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Begin!!";
                    this.mUIBeginWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIBeginWindow.WindowTitles.Add("The Story");
                    #endregion
                }
                return this.mUIBeginWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUINextWindow;
        
        private WinWindow mUIBeginWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICloud9Level1Window : WinWindow
    {
        
        public UICloud9Level1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Cloud 9 - Level 1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Cloud 9 - Level 1");
            #endregion
        }
        
        #region Properties
        public UICloud9Level1Client UICloud9Level1Client
        {
            get
            {
                if ((this.mUICloud9Level1Client == null))
                {
                    this.mUICloud9Level1Client = new UICloud9Level1Client(this);
                }
                return this.mUICloud9Level1Client;
            }
        }
        #endregion
        
        #region Fields
        private UICloud9Level1Client mUICloud9Level1Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICloud9Level1Client : WinClient
    {
        
        public UICloud9Level1Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Cloud 9 - Level 1";
            this.WindowTitles.Add("Cloud 9 - Level 1");
            #endregion
        }
        
        #region Properties
        public WinWindow UIBackgroundWindow
        {
            get
            {
                if ((this.mUIBackgroundWindow == null))
                {
                    this.mUIBackgroundWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIBackgroundWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
                    this.mUIBackgroundWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "33";
                    this.mUIBackgroundWindow.WindowTitles.Add("Cloud 9 - Level 1");
                    #endregion
                }
                return this.mUIBackgroundWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIBackgroundWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDeathBoxWindow : WinWindow
    {
        
        public UIDeathBoxWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "DeathBox";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("DeathBox");
            #endregion
        }
        
        #region Properties
        public UIDeathBoxClient UIDeathBoxClient
        {
            get
            {
                if ((this.mUIDeathBoxClient == null))
                {
                    this.mUIDeathBoxClient = new UIDeathBoxClient(this);
                }
                return this.mUIDeathBoxClient;
            }
        }
        
        public UIContinueWindow UIContinueWindow
        {
            get
            {
                if ((this.mUIContinueWindow == null))
                {
                    this.mUIContinueWindow = new UIContinueWindow(this);
                }
                return this.mUIContinueWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIDeathBoxClient mUIDeathBoxClient;
        
        private UIContinueWindow mUIContinueWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDeathBoxClient : WinClient
    {
        
        public UIDeathBoxClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "DeathBox";
            this.WindowTitles.Add("DeathBox");
            #endregion
        }
        
        #region Properties
        public WinWindow UIContinueWindow
        {
            get
            {
                if ((this.mUIContinueWindow == null))
                {
                    this.mUIContinueWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIContinueWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Continue";
                    this.mUIContinueWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIContinueWindow.WindowTitles.Add("DeathBox");
                    #endregion
                }
                return this.mUIContinueWindow;
            }
        }
        
        public WinWindow UIExitGameWindow
        {
            get
            {
                if ((this.mUIExitGameWindow == null))
                {
                    this.mUIExitGameWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIExitGameWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Exit Game";
                    this.mUIExitGameWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIExitGameWindow.WindowTitles.Add("DeathBox");
                    #endregion
                }
                return this.mUIExitGameWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIContinueWindow;
        
        private WinWindow mUIExitGameWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIContinueWindow : WinWindow
    {
        
        public UIContinueWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button1";
            this.WindowTitles.Add("DeathBox");
            #endregion
        }
        
        #region Properties
        public WinButton UIContinueButton
        {
            get
            {
                if ((this.mUIContinueButton == null))
                {
                    this.mUIContinueButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIContinueButton.SearchProperties[WinButton.PropertyNames.Name] = "Continue";
                    this.mUIContinueButton.WindowTitles.Add("DeathBox");
                    #endregion
                }
                return this.mUIContinueButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIContinueButton;
        #endregion
    }
}
